# Generated by Django 5.0.3 on 2024-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='disciplina',
            field=models.TextField(max_length=100),
        ),
    ]
