# Generated by Django 5.0.3 on 2024-04-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_disciplina_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='num_sala',
        ),
    ]
