# Generated by Django 5.0.4 on 2024-05-26 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_avisos_horario_alter_turma_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisos',
            name='ano',
        ),
        migrations.AddField(
            model_name='avisos',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='avisos',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avisos',
            name='turma',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='myapp.turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hora_aula'),
        ),
        migrations.AlterField(
            model_name='avisos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.disciplina'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='hora_aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hora_aula'),
        ),
    ]
